version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bis-backend
    ports:
      - "8000:8000"
    env_file:
      - .env   # inject all variables from your local .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/serviceAccountKey.json
    volumes:
      - ./backend/serviceAccountKey.json:/app/serviceAccountKey.json
      - ./config:/app/config
    restart: unless-stopped
