// 🔧 Common link definitions
const links = {
  dashboard: (path) => ({ path, label: "🏠 Dashboard", action: "viewDashboard" }),
  residents: { path: "/residents", label: "👥 Residents", action: "manageResidents" },
  addResident: { path: "/residents/new", label: "➕ Add Resident", action: "manageResidents" },
  businesses: { path: "/businesses", label: "💼 Businesses", action: "viewBusinesses" },
  ownBusinesses: { path: "/businesses/my", label: "💼 My Businesses", action: "viewOwnBusinesses" },
  registerBusiness: { path: "/businesses/new", label: "➕ Register Business", action: "registerBusinesses" },
  registerResidentBusiness: { path: "/residentBusinesses", label: "➕ Register Resident Businesses", action: "registerResidentBusinesses" },
  documents: { path: "/documents", label: "📄 Documents", action: "viewDocuments" },
  ownDocuments: { path: "/ownDocuments", label: "📄 My Documents", action: "viewOwnDocuments" },
  
  requestDocument: { path: "/documents/request", label: "📝 Request Document", action: "requestDocuments" },
  incidents: { path: "/incidents", label: "⚠️ Incidents", action: "viewIncidents" },
  reportIncident: { path: "/incidents/new", label: "⚠️ Report Incident", action: "reportIncidents" },
  myIncidents: { path: "/myIncidents", label: "⚠️ My Incidents", action: "viewOwnIncidents" },
  fileComplaint: { path: "/complaints/new", label: "🗣️ File Complaint", action: "fileComplaints" },
  evaluateComplaints: { path: "/complaints/evaluate", label: "🗣️ Evaluate Complaints", action: "manageComplaints" },
  viewOwnComplaints: { path: "/myComplaints", label: "🗣️ My Complaints", action: "viewOwnComplaints" },
  viewAllComplaints: { path: "/allComplaints", label: "🗣️ Complaints", action: "viewAllComplaints" },
  createAccount: { path: "/accounts/new", label: "➕ Create Account", action: "createAccount" },
  treasurer: { path: "/treasurer", label: "💰 Finance", action: "viewFinancialRecords" },
  adminAudit: { path: "/admin/audit", label: "📊 Audit Center", action: "auditBarangayData" },
  dilgAuditOverview: { path: "/audit", label: "🕵️ Audit Overview", action: "auditBarangayData" },
  dilgAuditRegistry: { path: "/audit/registry", label: "📋 Registry Audit", action: "auditBarangayData" },
  dilgAuditDocuments: { path: "/audit/documents", label: "📑 Document Audit", action: "auditBarangayData" },
  dilgAuditExports: { path: "/audit/exports", label: "📤 Export Reports", action: "auditBarangayData" },
  cfdpSurvey: { path: "/cfdp-survey", label: "🧭 CFDP Survey", action: "viewCfdpSurvey" },
  skDashboard: { path: "/admin/youth", label: "🧒 Youth Oversight", action: "viewDashboard" },
  youth: { path: "/youth", label: "🏠 Dashboard", action: "viewDashboard" },
  youthRegistry: { path: "/youth/registry", label: "📋 Youth Registry", action: "viewDashboard" },
  youthPrograms: { path: "/youth/programs", label: "🎯 Programs", action: "viewDashboard" },
  youthAddProgram: { path: "/youth/programs/add", label: "➕ Add Program", action: "viewDashboard" },
  youthEvents: { path: "/youth/events", label: "📅 Events", action: "viewDashboard" },
  youthAddEvent: { path: "/youth/events/add", label: "➕ Add Event", action: "viewDashboard" },
  youthFeedback: { path: "/youth/feedback", label: "💬 Feedback", action: "viewDashboard" },
  home: { path: "/", label: "🏠 Home", action: "viewDashboard" },
  messages: { path: "/messages", label: "💬 Messages", action: "viewDashboard" },
  mySignature: { path: "/my-signature", label: "✍️ My Signature", action: "viewDashboard" },
  superAdmin: { path: "/super-admin", label: "🛡️ Barangays & Cities", action: "viewDashboard" },
  superAdminAccounts: { path: "/super-admin/accounts", label: "👥 Accounts", action: "viewDashboard" },
  superAdminPayments: { path: "/super-admin/payments", label: "💰 Payment Collections", action: "viewDashboard" },
  superAdminSettings: { path: "/super-admin/settings", label: "⚙️ Barangay Settings", action: "viewDashboard" },

  // Secretary-specific links
  requestForDocuments: { path: "/secretary/documents", label: "📝 Document Request", action: "documentRequest" },
  pendingRequests: { path: "/secretary/pending", label: "📋 Pending Requests", action: "pendingRequests" },
  paidRequests: { path: "/secretary/payments", label: "💳 Paid Requests", action: "paidRequests" },
  issuedDocuments: { path: "/secretary/issued", label: "✅ Issued Documents", action: "issuedDocuments" },
  rejectedRequests: { path: "/secretary/rejected", label: "❌ Rejected Requests", action: "rejectedRequests" },

  incomingPayments: { path: "/treasurer/incoming", label: "💳 Incoming Payments", action: "incomingPayments" },
  expenses: { path: "/treasurer/expenses", label: "💸 Expenses", action: "barangayExpenses" },
  reports: { path: "/treasurer/reports", label: "📊 Financial Reports", action: "financialReports" },
  settings: { path: "/treasurer/settings", label: "⚙️ Settings", action: "settings" },
};

const sidebarLinks = {
  super_admin: [
    links.superAdmin,
    links.superAdminAccounts,
    links.superAdminPayments,
    links.superAdminSettings,
    links.messages,
  ],
  admin: [
    links.dashboard("/admin"),
    links.messages,
    links.mySignature,
    links.adminAudit,
    links.skDashboard,
    links.cfdpSurvey,
    links.residents,
    links.businesses,
    links.documents,
    links.incidents,
    links.viewAllComplaints,   
    links.fileComplaint,
    links.createAccount,
    links.treasurer,
  ],
  staff: [
    links.dashboard("/staff"),
    links.messages,
    links.mySignature,
    links.cfdpSurvey,
    links.residents,
    links.addResident,
    links.businesses,
    links.registerResidentBusiness,
    links.incidents,
    links.viewAllComplaints,
    links.fileComplaint,
  ],
  surveyor: [
    links.messages,
    links.cfdpSurvey,
  ],
  supervisor: [
    links.messages,
    links.cfdpSurvey,
  ],
  secretary: [
    links.dashboard("/secretary"),
    links.messages,
    links.mySignature,
    links.cfdpSurvey,
    links.requestForDocuments,
    links.pendingRequests,
    links.paidRequests,
    links.issuedDocuments,
    links.documents,
    links.rejectedRequests,
  ],
  treasurer: [
    links.dashboard("/treasurer"),
    links.messages,
    links.mySignature,
    links.cfdpSurvey,
    links.incomingPayments,
    links.expenses,
    links.reports,
    links.settings,
  ],
  sk: [
    links.youth,
    links.messages,
    links.mySignature,
    links.youthRegistry,
    links.youthPrograms,
    links.youthAddProgram,
    links.youthEvents,
    links.youthAddEvent,
    links.youthFeedback,
    links.cfdpSurvey,
  ],
  dilg: [
    links.dilgAuditOverview,
    links.messages,
    links.dilgAuditRegistry,
    links.dilgAuditDocuments,
    links.dilgAuditExports,
    links.cfdpSurvey,
  ],
  resident: [
    links.dashboard("/resident"),
    links.messages,
    links.cfdpSurvey,
    links.fileComplaint,     
    links.viewOwnComplaints,   
    links.ownDocuments,
    links.requestDocument,
    links.registerBusiness,
    links.ownBusinesses,
    links.reportIncident,
    links.myIncidents,
  ],
  default: [
    links.home,
  ],
};

export default sidebarLinks;
